---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    fig_height: 7
    fig_width: 12
    keep_md: yes
---

## Loading and preprocessing the data
```{r}
library(ggplot2)
library(timeDate)
library(lattice)
unzip(zipfile = "activity.zip")
activity <- read.csv("activity.csv")
kroki <- activity$steps
dzien <- activity$date
inter <- activity$interval
activityWOna <- activity[!is.na(kroki),]
agregacja <- aggregate(list(kroki = kroki), list(dzien = dzien), FUN=sum)
agregacja2 <- aggregate(activityWOna$steps, list(activityWOna$interval), FUN=mean)
agregacja3 <- aggregate(activity$steps, list(activity$interval), mean, na.rm=T)
agregacjaZERO <- agregacja
agregacjaZERO[is.na(agregacjaZERO)] <- 0
agregacjaWOna <- agregacja[!is.na(agregacja$kroki),]

```
## What is mean total number of steps taken per day?
```{r}
## I use data without NA, but including 'zero-step' days
ggplot(data=agregacjaWOna, aes(agregacjaWOna$kroki))+geom_histogram(breaks=seq(0,25000,by=5000),col="blue",aes(fill=..count..))+scale_fill_gradient("count", low="white", high="red")+ggtitle("Histogram total number of steps without NA's")
summary(agregacjaWOna$kroki)

ggplot(data=agregacjaZERO, aes(agregacjaZERO$kroki))+geom_histogram(breaks=seq(0,25000,by=5000),col="blue",aes(fill=..count..))+scale_fill_gradient("count", low="white", high="red")+ggtitle("Histogram total number of steps with NA's")
summary(agregacja$kroki)

agregacjaAVG <- mean(agregacjaWOna$kroki)
agregacjaMEDIAN <- median(agregacjaWOna$kroki)

agregacjaAVG  # mean number of steps taken per day

agregacjaMEDIAN  # median number of steps taken per day

```

## What is the average daily activity pattern?
```{r}
plot(agregacja2$Group.1, agregacja2$x, type = "l",xlab="interval",ylab="avarage number of steps per day")

maximumSteps <- agregacja2[which.max(agregacja2$x),1]
maximumSteps # maximum steps during 5 munite period

```
## Imputing missing values
```{r}
val1 <- nrow(activity)
val2 <- nrow(activityWOna)
#Total number of NA's in the dataset
val1 - val2

activityNAreplaced <- activity
for (i in 1:nrow(activityNAreplaced)) {
  if (is.na(activityNAreplaced[i,1])) {
    activityNAreplaced[i,1] <- agregacja3[agregacja3$Group.1==activity[i,3],2]
  }
}

activityNAreplacedHIST <- tapply(activityNAreplaced$steps, activityNAreplaced$date, sum)
hist(activityNAreplacedHIST)

summary(activityNAreplacedHIST)

ggplot(data = agregacjaWOna, aes(x=dzien, y=kroki))+geom_bar(stat = "identity", fill="steelblue")+geom_text(aes(label=kroki),vjust=-0.3, size=3.5)+theme_minimal()+theme(axis.text.x = element_text(angle=90,hjust = 1))+ggtitle("Total number of steps per day (without zero-step days)")

ggplot(data = agregacjaZERO, aes(x=dzien, y=kroki))+geom_bar(stat = "identity", fill="steelblue")+geom_text(aes(label=kroki),vjust=-0.3, size=3.5)+theme_minimal()+theme(axis.text.x = element_text(angle=90,hjust = 1))+ggtitle("Total number of steps per day (with zero-step days)")
```


## Are there differences in activity patterns between weekdays and weekends?
```{r}
Sys.setlocale("LC_TIME", "English")
activityWEEKDAY <- activityNAreplaced
activityWEEKDAYvect <- as.Date(activityNAreplaced$date)
activityWEEKDAYvect <- ifelse(weekdays(activityWEEKDAYvect) %in% c('Saturday','Sunday'), 'weekday', 'weekend')
activityWEEKDAY <- cbind(activityWEEKDAY, activityWEEKDAYvect)

activityWEEKDAYplot <-aggregate(list(steps=activityWEEKDAY$steps), list(daytype = activityWEEKDAY$activityWEEKDAYvect, interval = activityWEEKDAY$interval), mean, na.rm=T)
xyplot(steps ~ interval | daytype , data = activityWEEKDAYplot, layout = c(1, 2), type="l", ylab="Number of steps")
```


